import * as MyTimes from "../src/index";
import * as AWS from "./constants/AWS";
import * as DATES from "./constants/DATES";

beforeEach(() => {
  expect(new Date(Date.now()).getFullYear()).toBeGreaterThanOrEqual(2022);
  jest.useFakeTimers();
});

afterEach(() => {
  jest.runOnlyPendingTimers();
  jest.useRealTimers();
  expect(new Date(Date.now()).getFullYear()).toBeGreaterThanOrEqual(2022);
});

test("now hour in AWSRegionCode 1999_12_31_23_59", () => {
  jest.setSystemTime(new Date(DATES.DATE_1999_12_31_23_59));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(21);
});

test("now hour in AWSRegionCode 2000_01_01_00_00", () => {
  jest.setSystemTime(new Date(DATES.DATE_2000_01_01_00_00));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(22);
});

test("now hour in AWSRegionCode 2001_01_01_01_02", () => {
  jest.setSystemTime(new Date(DATES.DATE_2001_01_01_01_02));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(23);
});

test("now hour in AWSRegionCode 2002_02_02_02_04", () => {
  jest.setSystemTime(new Date(DATES.DATE_2002_02_02_02_04));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(0);
});

test("now hour in AWSRegionCode 2003_03_03_03_06", () => {
  jest.setSystemTime(new Date(DATES.DATE_2003_03_03_03_06));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(0);
});

test("now hour in AWSRegionCode 2004_04_04_04_08", () => {
  jest.setSystemTime(new Date(DATES.DATE_2004_04_04_04_08));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(1);
});

test("now hour in AWSRegionCode 2005_05_05_05_10", () => {
  jest.setSystemTime(new Date(DATES.DATE_2005_05_05_05_10));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(2);
});

test("now hour in AWSRegionCode 2006_06_06_06_12", () => {
  jest.setSystemTime(new Date(DATES.DATE_2006_06_06_06_12));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(3);
});

test("now hour in AWSRegionCode 2007_07_07_07_14", () => {
  jest.setSystemTime(new Date(DATES.DATE_2007_07_07_07_14));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(4);
});

test("now hour in AWSRegionCode 2008_08_08_08_16", () => {
  jest.setSystemTime(new Date(DATES.DATE_2008_08_08_08_16));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(5);
});

test("now hour in AWSRegionCode 2009_09_09_09_18", () => {
  jest.setSystemTime(new Date(DATES.DATE_2009_09_09_09_18));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(6);
});

test("now hour in AWSRegionCode 2010_10_10_10_20", () => {
  jest.setSystemTime(new Date(DATES.DATE_2010_10_10_10_20));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(7);
});

test("now hour in AWSRegionCode 2011_11_11_11_22", () => {
  jest.setSystemTime(new Date(DATES.DATE_2011_11_11_11_22));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(9);
});

test("now hour in AWSRegionCode 2012_12_12_12_24", () => {
  jest.setSystemTime(new Date(DATES.DATE_2012_12_12_12_24));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(10);
});

test("now hour in AWSRegionCode 2013_03_13_13_26", () => {
  jest.setSystemTime(new Date(DATES.DATE_2013_03_13_13_26));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(10);
});

test("now hour in AWSRegionCode 2014_04_14_14_28", () => {
  jest.setSystemTime(new Date(DATES.DATE_2014_04_14_14_28));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(11);
});

test("now hour in AWSRegionCode 2015_05_15_15_30", () => {
  jest.setSystemTime(new Date(DATES.DATE_2015_05_15_15_30));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(12);
});

test("now hour in AWSRegionCode 2016_06_16_16_32", () => {
  jest.setSystemTime(new Date(DATES.DATE_2016_06_16_16_32));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(13);
});

test("now hour in AWSRegionCode 2017_07_17_17_34", () => {
  jest.setSystemTime(new Date(DATES.DATE_2017_07_17_17_34));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(18);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(14);
});

test("now hour in AWSRegionCode 2018_08_18_18_36", () => {
  jest.setSystemTime(new Date(DATES.DATE_2018_08_18_18_36));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(11);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(15);
});

test("now hour in AWSRegionCode 2019_09_19_19_38", () => {
  jest.setSystemTime(new Date(DATES.DATE_2019_09_19_19_38));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(16);
});

test("now hour in AWSRegionCode 2020_02_20_20_40", () => {
  jest.setSystemTime(new Date(DATES.DATE_2020_02_20_20_40));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(12);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(15);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(17);
});

test("now hour in AWSRegionCode 2021_01_21_21_42", () => {
  jest.setSystemTime(new Date(DATES.DATE_2021_01_21_21_42));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(13);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(21);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(18);
});

test("now hour in AWSRegionCode 2022_02_22_22_44", () => {
  jest.setSystemTime(new Date(DATES.DATE_2022_02_22_22_44));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(14);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(4);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(22);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(19);
});

test("now hour in AWSRegionCode 2023_03_23_23_46", () => {
  jest.setSystemTime(new Date(DATES.DATE_2023_03_23_23_46));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(16);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(5);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(19);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(23);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(0);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(20);
});

test("now hour in AWSRegionCode 2024_04_24_00_48", () => {
  jest.setSystemTime(new Date(DATES.DATE_2024_04_24_00_48));
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_2)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_E_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_1)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_US_W_2)).toEqual(17);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AF_S_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_E_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_3)).toEqual(7);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_S_1)).toEqual(6);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_3)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_2)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_SE_2)).toEqual(10);
  expect(MyTimes.nowHourInAWS(AWS.AWS_AP_NE_1)).toEqual(9);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CA_C_1)).toEqual(20);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_N_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_CN_NW_1)).toEqual(8);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_C_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_1)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_2)).toEqual(1);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_S_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_W_3)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_EU_N_1)).toEqual(2);
  expect(MyTimes.nowHourInAWS(AWS.AWS_ME_S_1)).toEqual(3);
  expect(MyTimes.nowHourInAWS(AWS.AWS_SA_E_1)).toEqual(21);
});
