[
  { name: "Ohio", code: "us-east-2", tz: "America/New_York" },
  { name: "Virginia", code: "us-east-1", tz: "America/New_York" },
  { name: "California", code: "us-west-1", tz: "America/Los_Angeles" },
  { name: "Oregon", code: "us-west-2", tz: "America/Los_Angeles" },
  { name: "Cape Town", code: "af-south-1", tz: "Africa/Cairo" },
  { name: "Hong Kong", code: "ap-east-1", tz: "Asia/Hong_Kong" },
  { name: "Jakarta", code: "ap-southeast-3", tz: "Asia/Jakarta" },
  { name: "Mumbai", code: "ap-south-1", tz: "Asia/Kolkata" },
  { name: "Osaka", code: "ap-northeast-3", tz: "Asia/Tokyo" },
  { name: "Seoul", code: "ap-northeast-2", tz: "Asia/Seoul" },
  { name: "Singapore", code: "ap-southeast-1", tz: "Asia/Singapore" },
  { name: "Sydney", code: "ap-southeast-2", tz: "Australia/Sydney" },
  { name: "Tokyo", code: "ap-northeast-1", tz: "Asia/Tokyo" },
  { name: "Montreal", code: "ca-central-1", tz: "America/Toronto" },
  { name: "Beijing", code: "cn-north-1", tz: "Asia/Shanghai" },
  { name: "Ningxia", code: "cn-northwest-1", tz: "Asia/Shanghai" },
  { name: "Frankfurt", code: "eu-central-1", tz: "Europe/Berlin" },
  { name: "Dublin", code: "eu-west-1", tz: "Europe/Dublin" },
  { name: "London", code: "eu-west-2", tz: "Europe/London" },
  { name: "Milan", code: "eu-south-1", tz: "Europe/Rome" },
  { name: "Paris", code: "eu-west-3", tz: "Europe/Paris" },
  { name: "Stockholm", code: "eu-north-1", tz: "Europe/Stockholm" },
  { name: "Manama", code: "me-south-1", tz: "Asia/Riyadh" },
  { name: "São Paulo", code: "sa-east-1", tz: "America/Sao_Paulo" },
];
