import { IANATimeZone } from "./types/iana-tz";
import { AWSRegionCode } from "./types/aws-region-codes";

export default function nowHour(): number;
export default function nowHourIn(tz: IANATimeZone): number;
export default function nowHourInAWS(awsrc: AWSRegionCode): number;
export default function isDayTime(): boolean;
export default function isDayTimeIn(tz: IANATimeZone): boolean;
export default function isDayTimeInAWS(awsrc: AWSRegionCode): boolean;
export default function isNightTime(): boolean;
export default function isNightTimeIn(tz: IANATimeZone): boolean;
export default function isNightTimeInAWS(awsrc: AWSRegionCode): boolean;
export default function isNight(): boolean;
export default function isNightIn(tz: IANATimeZone): boolean;
export default function isNightInAWS(awsrc: AWSRegionCode): boolean;
export default function isMorning(): boolean;
export default function isMorningIn(tz: IANATimeZone): boolean;
export default function isMorningInAWS(awsrc: AWSRegionCode): boolean;
export default function isAfternoon(): boolean;
export default function isAfternoonIn(tz: IANATimeZone): boolean;
export default function isAfternoonInAWS(awsrc: AWSRegionCode): boolean;
export default function isEvening(): boolean;
export default function isEveningIn(tz: IANATimeZone): boolean;
export default function isEveningInAWS(awsrc: AWSRegionCode): boolean;
export default function isBusinessHours(): boolean;
export default function isBusinessHoursIn(tz: IANATimeZone): boolean;
export default function isBusinessHoursInAWS(awsrc: AWSRegionCode): boolean;
export default function isDayShift(): boolean;
export default function isDayShiftIn(tz: IANATimeZone): boolean;
export default function isDayShiftInAWS(awsrc: AWSRegionCode): boolean;
export default function isEveningShift(): boolean;
export default function isEveningShiftIn(tz: IANATimeZone): boolean;
export default function isEveningShiftInAWS(awsrc: AWSRegionCode): boolean;
export default function isNightShift(): boolean;
export default function isNightShiftIn(tz: IANATimeZone): boolean;
export default function isNightShiftInAWS(awsrc: AWSRegionCode): boolean;
